### ISSUE TITLE
markdown 的样式如果自定义怎么整？

### ISSUE THREAD

**Issue by OHeroJ** [673800357/mpvue-wemark#1]

**Comment by flytam** [comment]
自定义具体是指？正常markdown预览出来的不是一样的吗

**Comment by OHeroJ** [comment]
就是 wemark.vue 里面的 css 样式我想自己定义, 比如使用[这一套](https://github.com/simonlc/Markdown-CSS)，特别的是语法高亮这块。

**Comment by flytam** [comment]
我这边是之前wemark没有mpvue的时候做的适配，核心实现还是这边[wemark](https://github.com/TooBug/wemark)。我的想法大概是需要提供对外接口提供自定义类样式的功能，代码高亮wemark已经[实现了](https://github.com/TooBug/wemark/issues/25)。可以到那边直接看看，现在wemark也支持在mpvue中使用了

**Comment by OHeroJ** [comment]
> 我这边是之前wemark没有mpvue的时候做的适配，核心实现还是这边[wemark](https://github.com/TooBug/wemark)。我的想法大概是需要提供对外接口提供自定义类样式的功能，代码高亮wemark已经[实现了](https://github.com/TooBug/wemark/issues/25)。可以到那边直接看看，现在wemark也支持在mpvue中使用了

恩，谢谢，我是因 `wemark` 嵌入无效，然后寻找到这个库的，嵌入`wemark` 页面不渲染

**Comment by OHeroJ** [comment]
> > 我这边是之前wemark没有mpvue的时候做的适配，核心实现还是这边[wemark](https://github.com/TooBug/wemark)。我的想法大概是需要提供对外接口提供自定义类样式的功能，代码高亮wemark已经[实现了](https://github.com/TooBug/wemark/issues/25)。可以到那边直接看看，现在wemark也支持在mpvue中使用了
> 
> 恩，谢谢，我是因 `wemark` 嵌入无效，然后寻找到这个库的，嵌入`wemark` 页面不渲染

https://github.com/TooBug/wemark/issues/76#issuecomment-487267880
